include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:

  errors:
    todo: ignore
    invalid_annotation_target: ignore
    
linter:
  rules:
    public_member_api_docs: false